import os
import time

os.system("clear")

print("      .+------+")
print("    .' |      |")
print("   +   |      |")
print("   |   |      |")
print("   |  .+------+")
print("   |.'      .'")
print("   +------+'")

time.sleep(1)
os.system("clear")

print("    +------+")
print("   /|      |")
print("  + |      |")
print("  | |      |")
print("  | +------+")
print("  |/      /")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+")
print("  |      |")
print("  +      +")
print("  |      |")
print("  +------+")
print("  |      |")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+ ")
print("  |      |\ ")
print("  |      | +")
print("  |      | |")
print("  +------+ |")
print("   \      \|")
print("    +------+")

time.sleep(1)
os.system("clear")

print("  +------+.")
print("  |      | `.")
print("  |      |   +")
print("  |      |   |")
print("  +------+.  |")
print("   `.      `.|")
print("     `+------+")

time.sleep(1)
os.system("clear")

print("      .+------+")
print("    .' |      |")
print("   +   |      |")
print("   |   |      |")
print("   |  .+------+")
print("   |.'      .'")
print("   +------+'")

time.sleep(1)
os.system("clear")

print("    +------+")
print("   /|      |")
print("  + |      |")
print("  | |      |")
print("  | +------+")
print("  |/      /")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+")
print("  |      |")
print("  +      +")
print("  |      |")
print("  +------+")
print("  |      |")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+ ")
print("  |      |\ ")
print("  |      | +")
print("  |      | |")
print("  +------+ |")
print("   \      \|")
print("    +------+")

time.sleep(1)
os.system("clear")

print("  +------+.")
print("  |      | `.")
print("  |      |   +")
print("  |      |   |")
print("  +------+.  |")
print("   `.      `.|")
print("     `+------+")

time.sleep(1)
os.system("clear")

print("      .+------+")
print("    .' |      |")
print("   +   |      |")
print("   |   |      |")
print("   |  .+------+")
print("   |.'      .'")
print("   +------+'")

time.sleep(1)
os.system("clear")

print("    +------+")
print("   /|      |")
print("  + |      |")
print("  | |      |")
print("  | +------+")
print("  |/      /")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+")
print("  |      |")
print("  +      +")
print("  |      |")
print("  +------+")
print("  |      |")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+ ")
print("  |      |\ ")
print("  |      | +")
print("  |      | |")
print("  +------+ |")
print("   \      \|")
print("    +------+")

time.sleep(1)
os.system("clear")

print("  +------+.")
print("  |      | `.")
print("  |      |   +")
print("  |      |   |")
print("  +------+.  |")
print("   `.      `.|")
print("     `+------+")

time.sleep(1)
os.system("clear")

print("      .+------+")
print("    .' |      |")
print("   +   |      |")
print("   |   |      |")
print("   |  .+------+")
print("   |.'      .'")
print("   +------+'")

time.sleep(1)
os.system("clear")

print("    +------+")
print("   /|      |")
print("  + |      |")
print("  | |      |")
print("  | +------+")
print("  |/      /")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+")
print("  |      |")
print("  +      +")
print("  |      |")
print("  +------+")
print("  |      |")
print("  +------+")

time.sleep(1)
os.system("clear")

print("  +------+ ")
print("  |      |\ ")
print("  |      | +")
print("  |      | |")
print("  +------+ |")
print("   \      \|")
print("    +------+")

time.sleep(1)
os.system("clear")

print("  +------+.")
print("  |      | `.")
print("  |      |   +")
print("  |      |   |")
print("  +------+.  |")
print("   `.      `.|")
print("     `+------+")

print("\n")
print("Bye!")
